---
title: "Analyzing Ethnic Origins of Holocaust Victims "
author: 
  - Navya Hooda 
thanks: "Code and data are available at: https://github.com/hoodanav/Holocaust-Analysis/tree/main and the shiny app is available here: https://4i3ihp-navya-hooda.shinyapps.io/shiny-app/"
date: today
date-format: long
abstract: "This discussion looks at the Holocaust using numbers to show how certain groups were specifically targeted and suffered immense loss. It considers how data can't fully capture the true impact on people's lives and reminds us to understand history deeply, with respect for individual stories. It's a stark reminder of the need to honor those affected by such tragedies and strive for a better world without them."
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
library(palmerpenguins)
```


# Introduction
The Holocaust, a time of unfathomable horrors and horrific suffering, is still one of the most inhuman events in history as a whole. The data presented offers a quantitative glimpse into the magnitude of this tragedy, providing statistics on the number of deportees, the percentage of victims within different categories, and the overall devastation inflicted upon millions of lives. However, as @citeHealy notes in his  discussion of quantitative data, numbers alone cannot capture the depth of human experience or the profound loss endured by individuals and communities during this horrific time.



# Data 
To analyze the Holocaust related statistics, data was found from @auschwitz an online source detailing the statistics on the ethnicities and nationalities of the victims,  number of deaths and prisoners. This data was used as csv to build a @citeShiny application using @citeR that summarizes the number of murders and deaths by ethnicities, the percentage of ethnicities targetted and the nationalities most victimized during the Holocaust period. 

## Application Findings
Demonstrated by the published application, the statistics demonstrate the targeted nature of the Holocaust, with certain groups experiencing significantly higher percentages of murder within their category. For example, the data reveals that 93% of Soviet POWs and 91.3% of Roma (Gypsies) were murdered, showcasing the deliberate and genocidal intent behind the Nazis' actions. Furthermore, the data sheds light on the disproportionate suffering of the Jewish population, with Jews comprising 85% of the total number of victims and 90% of the murdered victims. This stark disparity highlights the central role of anti-Semitism in driving the Holocaust and represents the realities of the tragedy faced by the Jewish community. Overall, the data serves as an important reminder of the horrors of the Holocaust and the importance of learning from this dark chapter in human history.


## Role of Data in Discussing Tradegies
The use of data in understanding tragedies by quantifying impact on topics like the Holocaust presents a complex ethical and emotional challenge. Similar to the perspective shared by Healy (2020), the data on the Holocaust statistics provides a quantitative foundation that tries to encapsulate the reality of the horror inflicted upon millions of individuals during the Holocaust. Altough these numbers may seem like a  However, it is crucial to recognize the limitations of such data in capturing the full depth of human suffering and loss experienced during this dark period in history. 


# Discussion 

As we grapple with the data and its implications, it is crucial to approach it with sensitivity and mindfulness of the human experiences it represents. The statistics, while important for understanding the scale of the Holocaust, must be complemented by narratives, testimonies, and historical context that humanize the victims and honor their memory. The data serves as a starting point, and a reminder of the necessity of remembrance and understanding to prevent such atrocities from ever happening again.
Referring to insights from [@citeNYT], it is important to digest data in history that may affect individuals today, with historical context and perspective. This not only allows a better understanding, but a sense of reality and connection to today's problems. In terms of the Holocaust, Bouie (2022) suggests that all data should be humanized and read in that perspective to allow learning, and honouring the people who suffered the tragedies. 


# Conclusion 

As we reflect on the data and grapple with its implications, it is essential to complement our analysis with narratives, testimonies, and historical context that humanize the victims and honor their memory. The data, therefore, serves not as a conclusion but as a starting point for deeper reflection and a reminder of the importance of remembering and understanding the past to ensure such atrocities are never repeated.


# References


